### ISSUE TITLE
Hypercasual game explore images missing

### ISSUE THREAD

**Issue by HiddenQueen2ohoh3** [nginetechnologies/sceneri-app#10]
Go into the category of hypercasual and 2 projects are missing their images.
<img width="716" alt="Screenshot 2024-10-15 at 12 02 59 PM" src="https://github.com/user-attachments/assets/f6d7a24a-d4ed-4e69-a5ce-cbf089bee806">

**Comment by Collingine** [comment]
This should be fixed in the latest version of the application. Thanks for pointing it out.
