### ISSUE TITLE
Cubely character is invisible

### ISSUE THREAD

**Issue by Kitbasher69** [nginetechnologies/sceneri-app#13]
![missing_cubely](https://github.com/user-attachments/assets/5237adee-a97f-475f-b5ed-3c5c70fed9da)

**Comment by Collingine** [comment]
All fixed
<img width="1311" alt="Screenshot 2024-10-23 at 2 07 07 PM" src="https://github.com/user-attachments/assets/5631b1f6-7b95-4ecb-81ab-d8c262d3e502">
