### ISSUE TITLE
Sponza dirt decal looks to be incorrectly setup material

### ISSUE THREAD

**Issue by HiddenQueen2ohoh3** [nginetechnologies/sceneri-app#9]
<img width="789" alt="Screenshot 2024-10-15 at 12 01 24 PM" src="https://github.com/user-attachments/assets/9508b28f-dc9e-4e7e-a585-fce4694d3221">

**Comment by Collingine** [comment]
This should be resolved in latest.
![Screenshot 2024-10-18 at 4 29 24 PM](https://github.com/user-attachments/assets/6d493a72-e5e8-4156-8818-4ace0eebf32b)
